### ISSUE TITLE
[MNK] Request: Feature to enable forced Twin Snakes / Demolish refreshes

### ISSUE THREAD

**Issue by BeetleLord** [MKhayle/XIVComboPlugin#206]
Lately I have been making an effort to master the standard looping rotation for Monk, and I've noticed that there are points in the rotation where you'd want to force a Twin Snakes or Demolish regardless of the amount of time left on the buff/debuff.

![image](https://user-images.githubusercontent.com/96172665/214780381-5a2f4141-8356-47ca-a3d0-25283aa1c5cf.png)

The standard loop contains the above during the odd-minute burst. At 3m, 5m, 7m (etc) you will have to do Twin Snakes, Demolish, Opo, Twin Snakes, which requires forcibly refreshing Twin Snakes at about 9s remaining. There's also the fact that you MUST refresh both Twin Snakes and Demolish just before the Opo-spam + Phantom Rush in the odd burst window.

Currently there is no way to forcibly refresh a Twin Snakes or Demolish when more than 6 seconds are remaining on the buff/debuff. To solve this, I would propose two new sub-features:

For the "Twin Snakes / True Strike" feature, add a sub-feature so that whenever the Twin Snakes button turns into True Strike, the True Strike button will also turn into Twin Snakes.
For the "Demolish / Snap Punch" feature, add a sub-feature so that whenever the Demolish button turns into Snap Punch, the Snap Punch button will turn into Demolish.

With these, the user can take advantage of the automatic selection in the 99% of cases where it's beneficial, and still have manual control for special cases.

EDIT: Made some initial mistakes with the skill names in the title/description and fixed it. Then changed the whole idea to a more universal solution.

**Comment by BeetleLord** [comment]
Please ignore, I can't fix the title and I somehow mentioned the wrong feature. Will repost

**Comment by Grammernatzi** [comment]
> For the "Twin Snakes / True Strike" feature, add a sub-feature so that whenever the Twin Snakes button turns into True Strike, the True Strike button will also turn into Twin Snakes.
For the "Demolish / Snap Punch" feature, add a sub-feature so that whenever the Demolish button turns into Snap Punch, the Snap Punch button will turn into Demolish.

Can't do this. The queueing system gets confused if an action is linked to another action that is currently changed. The only way this would work is if they used a separate action (like some random GLD skill) as the base transforming action.

**Comment by BeetleLord** [comment]
Hmm. I also tried getting around this using macros to no avail. Even actions queued from macros get overridden.

I would be perfectly fine with using some random skills as the base action, or specifying a hotkey (such as Shift) that, when held, reverses the action or turns it into a forced refresh action.

**Comment by BeetleLord** [comment]
If this feature is not viable, then I will propose another feature that would fix the issue of being unable to perform the looping rotation. This solution is based on the following assumptions:

1) Whenever you have the Lunar and Solar Nadi and you enter Riddle of Fire, you intend to execute the Opo-spam into Phantom Rush combo. That is: Opo, (PB) Opo, Opo, Opo, Phantom Rush (RoF falls off), Opo.

2) Just before this combo begins, you must refresh Twin Snakes and Demolish to ensure that they last through it.

3) There is always a Snap Punch executed at 16 seconds remaining in the RoF window. After that, all Raptor and Coeurl GCDs ought to be Twin Snakes or Demolish until the end of the PB window.

Given the above assumptions, a feature could be added that does the following:

When possessing both the Lunar and Solar Nadi and Riddle of Fire is active with less than 16 seconds remaining, force Raptor stance to activate Twin Snakes and force Coeurl stance to activate Demolish.

This would effectively ensure that you cannot drop Twin Snakes before Phantom Rush during the odd burst window. I still think the other recommendation would be great, however, this would at least make the standard rotation possible in the meantime if this is simpler to implement.

**Comment by Grammernatzi** [comment]
Honestly, the simplest solution would be just to make a separate feature that replaces true strike with twin snakes instead of the other way around (same with snap punch and demolish). That way you can still have twin snakes and demolish on your bar whenever you need to use them.

**Comment by kaedys** [comment]
I propose a simpler fix.  The current system turns Demolish into Snap Punch and Twin Snakes into True Strike, as needed.  Either invert that, or add an additional combo (exclusive with the existing one) that is the inverse.  In other words, Snap Punch turns into Demolish and True Strike turns into Twin Snakes, as needed.  That allows Demolish and Twin Snakes to be left on the bar as is, with one button being the "autoswap" one, and the other being the force refresh one.  While this precludes force-using True Strike and Snap Punch when the logic would normally select a refresh (ex. the boss is about to vanish, so refreshing is a waste), that is imo a less common need than force-refreshing early, which needs to be done before _most_ Elixir Field and Phantom Rush combos to ensure the Twin Snakes buff lasts the duration.

I'd personally just invert the existing logic, but as that would almost certainly disrupt existing users (since they'd have Twin Snakes and Demolish on their bars currently, not True Strike and Snap Punch), it may be _better_ to implement it as a second combo definition instead.  But as @Grammernatzi noted above, it definitely needs to be mutually exclusive, as bad things happen if you have a combo option on A that changes into B, which itself has a combo option defined on it.

**Comment by BeetleLord** [comment]
I agree that what you proposed is a viable fix that would be simpler and still good enough. Anything is better than leaving it in the current state which prevents playing MNK properly at all while using the most important XIVCombo features.

**Comment by MKhayle** [comment]
As of https://github.com/MKhayle/XIVComboPlugin/commit/053ff47c99d65bbc48515d05e81bd1a50502e9b1, I have added the following features : 
- **Formless Strike** [Child Option for True Strike / Twin Snakes Feature] (While Formless Fist is active, do not replace True Strike.)
- **Snap Punch / Demolish Feature** (Replace Snap Punch with Demolish if Demolish has less than 6s remaining on your current target or isn't applied yet)

Feel free to test those changes ; I'll let this issue open for some days so you have time to test it if you want to submit feedback.
