### ISSUE TITLE
Inconsistent Aetherflow detection 6.4

### ISSUE THREAD

**Issue by Jaesaces** [MKhayle/XIVComboPlugin#226]
It seems the Scholar "combos" that replace abilities with Aetherflow when you have no stacks are not behaving properly.  Namely, they're often acting as if you have no stacks when you do.

My apologies if this is due to issues with Test Dalamud rather than something necessitating a plugin update.

**Comment by Grammernatzi** [comment]
It is indeed a Dalamud issue at the moment, as I mentioned [here](https://github.com/daemitus/XIVComboPlugin/issues/227#issuecomment-1564172658). While it could be fixed with some rewriting of code, Dalamud itself will likely be fixed soon, as this is a base XIVCombo feature, so it has high priority.
