### ISSUE TITLE
#133 and #135 do not work together

### ISSUE THREAD

**Issue by HPDeskJet2540** [MKhayle/XIVComboPlugin#234]
#135 Fight or Fllight Goring Blade Feature does not work with #133 Requiescat Fight or Flight Feature

**Comment by MKhayle** [comment]
135 (**Fight or Flight Goring Blade Feature**) applies to 133 (**Requiescat Fight or Flight Feature**) correctly. 

The expected behaviour is that having 133 and 135 active at the same time will affect **Requiescat** to become **Fight or Flight** if it's available, then it becomes **Requiescat** if available, and it becomes **Goring Blade** before it gets replaced by **Confiteor** and then continues into the **Blades** combo.
